learning_log/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('',include('users.urls', namespace='users')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

learning_logs/urls.py
"""Defines URL patters for learning_logs."""

from django.urls import path
from . import views
from django.contrib.auth.views import LoginView


app_name = 'learning_logs'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    #Show all topics
    path('topics/', views.topics, name='topics'),

    #Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    #This is a page that will be used to add new topics
    path('new_topic/', views.new_topic, name = 'new_topic'),

    #This is a page that will be used to add new entries
    path('new_entries/<int:topic_id>', views.new_entries, name = 'new_entries'),

    #This is a page for edditing existing entries
    path('edit_entry/<int:entry_id>', views.edit_entry, name = 'edit_entry'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'

urlpatterns = [
    # Login page
    path('users/login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    #Logout page
    path('logout/', views.logout_view, name='logout'),
    #The registratoin page
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic that the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text
    
class Entry(models.Model):
    """something specific that is learned about a topic"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()

    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic
from .models import Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        lables = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Entry
from .forms import TopicForm
from .forms import EntryForm
# Create your views here.


def index(request):
    """The home page for learning log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {'topics' : topics}    
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries"""
    topic = Topic.objects.get(id=topic_id)
    #Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        #NO data has been submitted; create a blank form.
        form = TopicForm()
    else:
        #POST data submitted, so process that data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entries(request, topic_id):
    """Add a new entry"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # NO data has been submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted, so process that data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', kwargs={'topic_id': topic_id}))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entries.html', context)

@login_required
def edit_entry(request, entry_id):
    """Editing an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #NO data has been submitted, so keep the current entry
        form = EntryForm(instance=entry)
    else:
        #POST data has ben submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic , 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    """Log the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

def register(request):
    if request.method != 'POST':
        #Display a blank registratoin form
        form = UserCreationForm()
    else:
        #Process the completed form
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            #Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form' : form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title> 
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        /* Add custom styles here */
    .navbar-brand {
        font-weight: bold;
        font-size: 24px;
        padding: 5px 15px; /* Adjust the padding as needed */
    }

    .navbar-brand img {
        max-height: 100%; /* Set the maximum height of the logo image */
        max-width: 100%; /* Set the maximum width of the logo image */
        vertical-align: middle; /* Align the logo vertically */
    }

        .navbar-brand {
            font-weight: bold;
            font-size: 24px;
        }

        .navbar-default {
            background-color: #f8f8f8;
            border-color: #e7e7e7;
        }

        .navbar-default .navbar-nav > li > a {
            color: #333;
        }

        .navbar-default .navbar-nav > li > a:hover,
        .navbar-default .navbar-nav > li > a:focus {
            color: #555;
            background-color: transparent;
        }

        .navbar-default .navbar-nav > .active > a,
        .navbar-default .navbar-nav > .active > a:hover,
        .navbar-default .navbar-nav > .active > a:focus {
            color: #555;
            background-color: #e7e7e7;
        }

        .navbar-default .navbar-toggle .icon-bar {
            background-color: #333;
        }

        .page-header {
            margin-top: 40px;
        }

        .footer {
            background-color: #f8f8f8;
            padding: 20px;
            text-align: center;
        }
    </style>
</head>
<body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                    <img src= "{% static 'images/logo.png' %}" alt="logo"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">Register</a></li>
                        <li><a href="{% url 'users:login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div> 
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->
    <footer class="footer">
        <p> This website is developed by Saai Arora, check out more stuff by him here: <a href="https://github.com/Saai151">Projects</a>
        </p>
    </footer>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
     <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

     <p>Edit entry:</p>

     <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'> 
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
     </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class='jumbotron'>
       <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}
    {% if user.is_authenticated %}
        <h2>
            Welcome, {{ user.username }}! Start using Learning Logs and list the topics you're learning about.
        </h2>
    {% else %}
        <h2>
            <a href="{% url 'users:register' %}">Register</a> to make your own Learning Log, and list the topics you're learning about.
        </h2> 
    {% endif %}
    
    <h2>
       Whenever you learn something new about a topic, make an entry
       summarizing what you've learned.
    </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entries.html
{% extends "learning_logs/base.html" %}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entries' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>add entry</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %} 
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entries' topic.id %}">add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
              edit entry</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
    {% empty %}
    There are no entries for this topic yet.
  {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %} 
    <h1>Topics</h1>
{% endblock header %}
   
{% block content %}
     <ul>
       {% for topic in topics %}
        <li>
            <h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </h3>
        </li>
    {% empty %}
        <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</h3>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}

{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="btn-group" role="group" aria-label="Login and Register Buttons">
            <button name="submit" class="btn btn-primary ml-2">Log in</button>
            <a href="{% url 'users:register' %}" class="btn btn-primary">Register</a>
        </div>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}"> 
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">register</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" /> 
    </form>
{% endblock content %}